version: "3"
services:
  app:
    container_name: mernblogui
    build: ./client
    ports:
      - "3000:3000"
  json-server:
    container_name: mernblogserver
    build: ./Server
    ports:
      - "4000:4000"